version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example-app_1
    volumes:
      - ./:/var/www/html
    ports:
      - "8088:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db_1
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin_1
    container_name: phpmy
    restart: always
    depends_on:
      - db
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db_data:
