version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example-app_3
    volumes:
      - ./:/var/www/html
    ports:
      - "8083:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_d
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: php/phpmyadmin:latest
    container_name: phpmy
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db_data:
